# Generated by Django 4.2.5 on 2023-09-30 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashMoneyChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_company', models.CharField(choices=[('1', 'Electricity'), ('2', 'Water'), ('3', 'Phone')], max_length=100)),
                ('user_role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('superadmin', 'Manage')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Staduims',
            fields=[
                ('Staduim_id', models.AutoField(primary_key=True, serialize=False)),
                ('Staduim_name', models.CharField(max_length=50, unique=True)),
                ('Ticket_Price', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('Capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('1', 'Deposit'), ('2', 'Withdrawal'), ('3', 'Transfer')], default='1')),
                ('status', models.CharField(choices=[('1', 'Pending'), ('2', 'Completed'), ('3', 'Failed')], default='2')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to=settings.AUTH_USER_MODEL), on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('1', 'Pending'), ('2', 'Completed'), ('3', 'Failed')])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Stauim_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.staduims', to_field='Staduim_name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('log_type', models.CharField(choices=[('1', 'Deposit'), ('2', 'Withdrawal'), ('3', 'Transfer'), ('4', 'Bill Payment'), ('5', 'Ticket Payment'), ('6', 'Login'), ('7', 'Create Account'), ('8', 'LogOut')])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_type', models.CharField(choices=[('1', 'Electricity'), ('2', 'Water'), ('3', 'Phone')], max_length=255)),
                ('payment_status', models.CharField(choices=[('1', 'Pending'), ('2', 'Completed'), ('3', 'Failed')])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
