# Generated by Django 4.2.5 on 2023-10-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_billpayment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billpayment',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('1', 'Pending'), ('2', 'Completed'), ('3', 'Failed')]),
        ),
    ]
