# Generated by Django 4.2.5 on 2023-10-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_billpayment_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Pending'), ('2', 'Completed'), ('3', 'Failed')]),
        ),
    ]
